import React, { createContext, useContext, useState } from 'react';

/**
 * LanguageContext - Bilingual support for Jal Nivaran Dashboard
 * Compliant with Official Languages Act (English / Hindi)
 */
const LanguageContext = createContext();

// Official Government Hindi Translations Dictionary
const translations = {
  en: {
    // Status Labels
    highRisk: 'High Risk',
    mediumRisk: 'Medium Risk',
    lowRisk: 'Low Risk',
    critical: 'Critical',
    normal: 'Normal',
    safe: 'Safe',
    
    // Headings
    delhiFloodRiskMap: 'Delhi Flood Risk Map',
    monsoonMonth: 'Monsoon Month',
    emergencyResources: 'Emergency Resources',
    dailySituationReport: 'Daily Situation Report',
    dashboard: 'Monsoon Flood Risk Assessment Dashboard',
    riskAssessment: 'Risk Assessment',
    
    // Actions
    deployTeam: 'Deploy Team',
    downloadReport: 'Download Report',
    downloadDSR: 'Download DSR (PDF)',
    viewDetails: 'View Details',
    generateReport: 'Generate Report',
    
    // Components
    floodMap: 'Flood Map',
    riskScore: 'Risk Score',
    projectedRiskScore: 'Projected Risk Score',
    riskCategory: 'Risk Category',
    vulnerableWards: 'Vulnerable Wards',
    affectedPopulation: 'Affected Population',
    deployedTeams: 'Deployed Teams',
    activeComplaints: 'Active Complaints',
    
    // Time & Weather
    timeToFlood: 'Time-to-Flood Estimate',
    rainfall: 'Rainfall',
    rainfallRate: 'Rainfall Rate',
    remainingBuffer: 'Remaining Buffer',
    hours: 'hours',
    monitorClosely: 'Monitor closely',
    
    // Emergency
    quickAction: 'Quick Action',
    deployPumps: 'Deploy pumps and clear priority drains now',
    emergencyTeams: 'Emergency Teams',
    availableResources: 'Available Resources',
    
    // Locations
    karolBagh: 'Karol Bagh',
    chandniChowk: 'Chandni Chowk',
    dwarka: 'Dwarka',
    rohini: 'Rohini',
    sarojiniNagar: 'Sarojini Nagar',
    
    // Water & Drainage
    waterlogging: 'Waterlogging',
    drainageCapacity: 'Drainage Capacity',
    pumpStations: 'Pump Stations',
    floodProne: 'Flood-Prone',
    
    // Report Terms
    generatedBy: 'Generated by',
    reportDate: 'Report Date',
    officialUse: 'Official Use Only',
    confidential: 'CONFIDENTIAL',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    close: 'Close',
    submit: 'Submit',
    cancel: 'Cancel',
    
    // Header
    municipalCorporation: 'Municipal Corporation of Delhi',
    jalNivaranPortal: 'Jal Nivaran Portal',
    floodManagement: 'Flood Management System',
    
    // Units
    mm: 'mm',
    mmPerHour: 'mm/hr',
    percentage: '%',
    teams: 'Teams',
    wards: 'Wards',
  },
  
  hi: {
    // Status Labels
    highRisk: 'उच्च जोखिम (High Risk)',
    mediumRisk: 'मध्यम जोखिम',
    lowRisk: 'सुरक्षित (Safe)',
    critical: 'गंभीर',
    normal: 'सामान्य',
    safe: 'सुरक्षित',
    
    // Headings
    delhiFloodRiskMap: 'दिल्ली बाढ़ जोखिम मानचित्र',
    monsoonMonth: 'मानसून माह',
    emergencyResources: 'आपातकालीन संसाधन',
    dailySituationReport: 'दैनिक स्थिति रिपोर्ट (DSR)',
    dashboard: 'मानसून बाढ़ जोखिम मूल्यांकन डैशबोर्ड',
    riskAssessment: 'जोखिम मूल्यांकन',
    
    // Actions
    deployTeam: 'टीम भेजें',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    downloadDSR: 'DSR डाउनलोड करें (PDF)',
    viewDetails: 'विवरण देखें',
    generateReport: 'रिपोर्ट बनाएं',
    
    // Components
    floodMap: 'बाढ़ मानचित्र',
    riskScore: 'जोखिम स्कोर',
    projectedRiskScore: 'अनुमानित जोखिम स्कोर',
    riskCategory: 'जोखिम श्रेणी',
    vulnerableWards: 'संवेदनशील वार्ड',
    affectedPopulation: 'प्रभावित जनसंख्या',
    deployedTeams: 'तैनात टीमें',
    activeComplaints: 'सक्रिय शिकायतें',
    
    // Time & Weather
    timeToFlood: 'बाढ़ आने का अनुमानित समय',
    rainfall: 'वर्षा',
    rainfallRate: 'वर्षा दर',
    remainingBuffer: 'शेष बफर',
    hours: 'घंटे',
    monitorClosely: 'बारीकी से निगरानी करें',
    
    // Emergency
    quickAction: 'त्वरित कार्रवाई',
    deployPumps: 'पंप तैनात करें और प्राथमिकता नालियों को साफ करें',
    emergencyTeams: 'आपातकालीन टीमें',
    availableResources: 'उपलब्ध संसाधन',
    
    // Locations (Keep English names, add Hindi descriptor)
    karolBagh: 'करोल बाग',
    chandniChowk: 'चांदनी चौक',
    dwarka: 'द्वारका',
    rohini: 'रोहिणी',
    sarojiniNagar: 'सरोजिनी नगर',
    
    // Water & Drainage
    waterlogging: 'जल-जमाव',
    drainageCapacity: 'जल निकासी क्षमता',
    pumpStations: 'पंप स्टेशन',
    floodProne: 'बाढ़-प्रवण',
    
    // Report Terms
    generatedBy: 'द्वारा उत्पन्न',
    reportDate: 'रिपोर्ट दिनांक',
    officialUse: 'केवल आधिकारिक उपयोग',
    confidential: 'गोपनीय',
    
    // Common
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    warning: 'चेतावनी',
    info: 'जानकारी',
    close: 'बंद करें',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    
    // Header
    municipalCorporation: 'दिल्ली नगर निगम (MCD)',
    jalNivaranPortal: 'जल निवारण पोर्टल',
    floodManagement: 'बाढ़ प्रबंधन प्रणाली',
    
    // Units (Keep as is for clarity)
    mm: 'मिमी',
    mmPerHour: 'मिमी/घंटा',
    percentage: '%',
    teams: 'टीमें',
    wards: 'वार्ड',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // Default: English

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  // Translation helper function with fallback
  const t = (key) => {
    const translation = translations[language]?.[key];
    
    // Fallback to English if translation not found
    if (!translation) {
      console.warn(`Translation missing for key: ${key} in language: ${language}`);
      return translations.en[key] || key;
    }
    
    return translation;
  };

  const value = {
    language,
    toggleLanguage,
    t,
    isHindi: language === 'hi',
    isEnglish: language === 'en'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for easy access
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  
  return context;
};

export default LanguageContext;
